### ISSUE TITLE
tianshou version issue

### ISSUE THREAD

**Issue by ArronDZhang** [chongminggao/DORL-codes#1]
Hi there,

I would be appreciated if you can tell me the version of tianshou I should reset to since when I follow the readme to reset tianshou with git reset --hard 0f59e38, it says fatal: ambiguous argument '0f59e38': unknown revision or path not in the working tree.

**Comment by chongminggao** [comment]
Sorry for the inconvenience caused. Now, You don't have to reset since I have reset my forked version (just like the following figure shown) and the HEAD now is at 0f59e38. So just omit this line `git reset --hard 0f59e38` in README.md. 
And I have deleted this line now! 

<img width="564" alt="issue1" src="https://github.com/chongminggao/DORL-codes/assets/11169881/bc99605f-cdee-4c8b-bf77-8e512fdaabb7">
